### ISSUE TITLE
Spaces between languages in the bar

### ISSUE THREAD

**Issue by fritzrehde** [idiotWu/stats#1]
Is there a way to get the spaces between each language in the languages bar back? The line `outline: 2px solid rgb(225, 228, 232);` in .progress-item in languages.svg seems to have been removed, which used to add this 2px space. However, I don't know how to add it back properly while keeping the transparency. Just replacing the line with `outline: 2px solid transparent;` does not seem to work (but I know nothing about svg so this could also just be a very naive approach).

**Comment by fritzrehde** [comment]
The spaces I mean can be seen [here](https://github.com/jstrieb/github-stats/blob/master/generated/languages.svg).

**Comment by dolphin-wood** [comment]
A quick fix is to use `margin` instead of `outline`:

```css
.progress-item:not(:last-child) {
    margin-right: 2px;
}
```

or use `padding` together with `background-clip`:

```css
.progress-item:not(:last-child) {
    padding-right: 2px;
    background-clip: content-box;
}
```
